import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/lib/authContext";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/navbar";
import { ModalProvider } from "@/providers/modal-provider";
import { SongsProvider } from "@/lib/songsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// const initialSongs = "Testing";
export default function RootLayout({ user, loading = false, children }: any) {
  return (
    <html lang="en">
      <UserProvider value={{ user, loading }}>
        <SongsProvider>
          <body className={inter.className}>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <Navbar />
              {children}
            </ThemeProvider>
          </body>
        </SongsProvider>
      </UserProvider>
    </html>
  );
}
